In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('income_evaluation.csv')
dataset.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [3]:
#I this part im gonna analyse each columns to figure out how to deal with them

In [4]:
#age
#doesn't need to change 'age' just assign the column to another variable to concatinate at the end of data preprocessing
X_age_final = dataset.iloc[:,0]

In [5]:
#workclass
X_workclass = dataset.iloc[:,1]
X_workclass.head()

0            State-gov
1     Self-emp-not-inc
2              Private
3              Private
4              Private
Name:  workclass, dtype: object

In [6]:
all_types_workclass = []
for item in X_workclass:
    if item in all_types_workclass:
        pass
    else:
        all_types_workclass.append(item)
print(all_types_workclass)

[' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov', ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay', ' Never-worked']


In [7]:
X_workclass_dummies = pd.get_dummies(X_workclass)
X_workclass_dummies

?   Federal-gov   Local-gov   Never-worked   Private   Self-emp-inc  \
0       0             0           0              0         0              0   
1       0             0           0              0         0              0   
2       0             0           0              0         1              0   
3       0             0           0              0         1              0   
4       0             0           0              0         1              0   
...    ..           ...         ...            ...       ...            ...   
32556   0             0           0              0         1              0   
32557   0             0           0              0         1              0   
32558   0             0           0              0         1              0   
32559   0             0           0              0         1              0   
32560   0             0           0              0         0              1   

        Self-emp-not-inc   State-gov   Without-pay  
0                      0           1             0  
1                      1           0             0  
2                      0           0             0  
3                      0           0             0  
4                      0           0             0  
...                  ...         ...           ...  
32556                  0           0             0  
32557                  0           0             0  
32558                  0           0             0  
32559                  0           0             0  
32560                  0           0             0  

[32561 rows x 9 columns]

In [8]:
counter = 0
for item in X_workclass:
    if item == ' ?':
        counter += 1

print(counter)

1836


In [9]:
X_workclass_dummies=X_workclass_dummies.drop(columns=' ?')

In [10]:
X_workclass_final = X_workclass_dummies.rename(columns={' Federal-gov':'WORKCLASS:Federal-gov',
                                                        ' Local-gov':'WORKCLASS:Local-gov',
                                                        ' Never-worked':'WORKCLASS:Never-worked',
                                                        ' Private':'WORKCLASS:Private',
                                                        ' Self-emp-inc':'WORKCLASS:Self-emp-inc',
                                                        ' Self-emp-not-inc':'WORKCLASS:Self-emp-not-inc',
                                                        ' State-gov':'WORKCLASS:State-gov',
                                                        ' Without-pay':'WORKCLASS:Without-pay',})
X_workclass_final

WORKCLASS:Federal-gov  WORKCLASS:Local-gov  WORKCLASS:Never-worked  \
0                          0                    0                       0   
1                          0                    0                       0   
2                          0                    0                       0   
3                          0                    0                       0   
4                          0                    0                       0   
...                      ...                  ...                     ...   
32556                      0                    0                       0   
32557                      0                    0                       0   
32558                      0                    0                       0   
32559                      0                    0                       0   
32560                      0                    0                       0   

       WORKCLASS:Private  WORKCLASS:Self-emp-inc  WORKCLASS:Self-emp-not-inc  \
0                      0                       0                           0   
1                      0                       0                           1   
2                      1                       0                           0   
3                      1                       0                           0   
4                      1                       0                           0   
...                  ...                     ...                         ...   
32556                  1                       0                           0   
32557                  1                       0                           0   
32558                  1                       0                           0   
32559                  1                       0                           0   
32560                  0                       1                           0   

       WORKCLASS:State-gov  WORKCLASS:Without-pay  
0                        1                      0  
1                        0                      0  
2                        0                      0  
3                        0                      0  
4                        0                      0  
...                    ...                    ...  
32556                    0                      0  
32557                    0                      0  
32558                    0                      0  
32559                    0                      0  
32560                    0                      0  

[32561 rows x 8 columns]

In [11]:
#final weight
X_fnlwgt = dataset.iloc[:,2]
print(min(X_fnlwgt))
print(max(X_fnlwgt))
X_fnlwgt_final = X_fnlwgt
# we dont need fnlwgt #because it is the numeric representation of the attribute education

12285
1484705


In [12]:
#   education
X_education = dataset.iloc[:,3]
all_types_education = []
for item in X_education:
    if item in all_types_education:
        pass
    else:
        all_types_education.append(item)
print(all_types_education)
print(len(all_types_education))

[' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th', ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th', ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th', ' Preschool', ' 12th']
16


In [13]:
''' we can rank these degree of educations from the lowest to the highest
    1- ' Preschool'
    2- ' 1st-4th'
    3- ' 5th-6th'
    4- ' 7th-8th'
    5- ' 9th'
    6- ' 10th'
    7- ' 11th'
    8- ' 12th'
    9- ' HS-grad'
    10- ' Prof-school'
    11- ' Assoc-acdm'
    12- ' Assoc-voc'
    13- 'Some-college'
    14- ' Bachelors'
    15- ' Masters'
    16- ' Doctorate'
    '''

" we can rank these degree of educations from the lowest to the highest\n    1- ' Preschool'\n    2- ' 1st-4th'\n    3- ' 5th-6th'\n    4- ' 7th-8th'\n    5- ' 9th'\n    6- ' 10th'\n    7- ' 11th'\n    8- ' 12th'\n    9- ' HS-grad'\n    10- ' Prof-school'\n    11- ' Assoc-acdm'\n    12- ' Assoc-voc'\n    13- 'Some-college'\n    14- ' Bachelors'\n    15- ' Masters'\n    16- ' Doctorate'\n    "

In [14]:
X_education_final = X_education.replace([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th', ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th', ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th', ' Preschool', ' 12th'],[14,9,7,15,5,13,11,12,4,16,10,3,6,2,1,8])

In [15]:
X_education_final

0        14
1        14
2         9
3         7
4        14
         ..
32556    11
32557     9
32558     9
32559     9
32560     9
Name:  education, Length: 32561, dtype: int64

In [16]:
# education number
# the data set education number is wrong by the refrence to https://sites.google.com/site/complexdataminingproject/ website
# I already satisfied the education num in the education part so we dont need this column.

In [17]:
# marital-status

In [18]:
X_marital_status = dataset.iloc[:,5]
all_types_marital_status = []
for item in X_marital_status:
    if item in all_types_marital_status:
        pass
    else:
        all_types_marital_status.append(item)
print(all_types_marital_status)
print(len(all_types_marital_status))

[' Never-married', ' Married-civ-spouse', ' Divorced', ' Married-spouse-absent', ' Separated', ' Married-AF-spouse', ' Widowed']
7


In [19]:
X_marital_status_dummies = pd.get_dummies(X_marital_status)
X_marital_status_dummies = X_marital_status_dummies.drop(columns=' Never-married')

In [20]:
X_marital_status_final = X_marital_status_dummies.rename(columns={' Never-married':'MARITAL_STATUS: Never-married',
                                                        ' Married-civ-spouse':'MARITAL_STATUS: Married-civ-spouse',
                                                        ' Divorced':'MARITAL_STATUS: Divorced',
                                                        ' Married-spouse-absent':'MARITAL_STATUS: Married-spouse-absent',
                                                        ' Separated':'MARITAL_STATUS: Separated',
                                                        ' Married-AF-spouse':'MARITAL_STATUS: Married-AF-spouse',
                                                        ' Widowed':'MARITAL_STATUS: Widowed',
                                                        })
X_marital_status_final

MARITAL_STATUS: Divorced  MARITAL_STATUS: Married-AF-spouse  \
0                             0                                  0   
1                             0                                  0   
2                             1                                  0   
3                             0                                  0   
4                             0                                  0   
...                         ...                                ...   
32556                         0                                  0   
32557                         0                                  0   
32558                         0                                  0   
32559                         0                                  0   
32560                         0                                  0   

       MARITAL_STATUS: Married-civ-spouse  \
0                                       0   
1                                       1   
2                                       0   
3                                       1   
4                                       1   
...                                   ...   
32556                                   1   
32557                                   1   
32558                                   0   
32559                                   0   
32560                                   1   

       MARITAL_STATUS: Married-spouse-absent  MARITAL_STATUS: Separated  \
0                                          0                          0   
1                                          0                          0   
2                                          0                          0   
3                                          0                          0   
4                                          0                          0   
...                                      ...                        ...   
32556                                      0                          0   
32557                                      0                          0   
32558                                      0                          0   
32559                                      0                          0   
32560                                      0                          0   

       MARITAL_STATUS: Widowed  
0                            0  
1                            0  
2                            0  
3                            0  
4                            0  
...                        ...  
32556                        0  
32557                        0  
32558                        1  
32559                        0  
32560                        0  

[32561 rows x 6 columns]

In [21]:
# occupation
X_occupation = dataset.iloc[:,6]
all_types_occupation = []
for item in X_occupation:
    if item in all_types_occupation:
        pass
    else:
        all_types_occupation.append(item)
print(all_types_occupation)
print(len(all_types_occupation))

[' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners', ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair', ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct', ' Tech-support', ' ?', ' Protective-serv', ' Armed-Forces', ' Priv-house-serv']
15


In [22]:
X_occupation_dummies = pd.get_dummies(X_occupation)
X_occupation_dummies = X_occupation_dummies.drop(columns=' ?')
X_occupation_dummies

Adm-clerical   Armed-Forces   Craft-repair   Exec-managerial  \
0                  1              0              0                 0   
1                  0              0              0                 1   
2                  0              0              0                 0   
3                  0              0              0                 0   
4                  0              0              0                 0   
...              ...            ...            ...               ...   
32556              0              0              0                 0   
32557              0              0              0                 0   
32558              1              0              0                 0   
32559              1              0              0                 0   
32560              0              0              0                 1   

        Farming-fishing   Handlers-cleaners   Machine-op-inspct  \
0                     0                   0                   0   
1                     0                   0                   0   
2                     0                   1                   0   
3                     0                   1                   0   
4                     0                   0                   0   
...                 ...                 ...                 ...   
32556                 0                   0                   0   
32557                 0                   0                   1   
32558                 0                   0                   0   
32559                 0                   0                   0   
32560                 0                   0                   0   

        Other-service   Priv-house-serv   Prof-specialty   Protective-serv  \
0                   0                 0                0                 0   
1                   0                 0                0                 0   
2                   0                 0                0                 0   
3                   0                 0                0                 0   
4                   0                 0                1                 0   
...               ...               ...              ...               ...   
32556               0                 0                0                 0   
32557               0                 0                0                 0   
32558               0                 0                0                 0   
32559               0                 0                0                 0   
32560               0                 0                0                 0   

        Sales   Tech-support   Transport-moving  
0           0              0                  0  
1           0              0                  0  
2           0              0                  0  
3           0              0                  0  
4           0              0                  0  
...       ...            ...                ...  
32556       0              1                  0  
32557       0              0                  0  
32558       0              0                  0  
32559       0              0                  0  
32560       0              0                  0  

[32561 rows x 14 columns]

In [23]:
X_occupation_final = X_occupation_dummies.rename(columns={
                                                 ' Adm-clerical':'OCP: Adm-clerical',
                                                 ' Exec-managerial':'OCP: Exec-managerial',
                                                 ' Handlers-cleaners':'OCP Handlers-cleaners',
                                                 ' Prof-specialty':'OCP: Prof-specialty',
                                                 ' Other-service':'OCP: Other-service',
                                                 ' Sales':'OCP: Sales',
                                                 ' Craft-repair':'OCP: Craft-repair',
                                                 ' Transport-moving':'OCP: Transport-moving',
                                                 ' Farming-fishing':'OCP: Farming-fishing',
                                                 ' Machine-op-inspct':'OCP: Machine-op-inspct',
                                                 ' Tech-support':'OCP: Tech-support',
                                                 ' Protective-serv':'OCP: Protective-serv',
                                                 ' Armed-Forces':'OCP: Armed-Forces',
                                                 ' Priv-house-serv':'OCP: Priv-house-serv'})

In [24]:
X_occupation_final

OCP: Adm-clerical  OCP: Armed-Forces  OCP: Craft-repair  \
0                      1                  0                  0   
1                      0                  0                  0   
2                      0                  0                  0   
3                      0                  0                  0   
4                      0                  0                  0   
...                  ...                ...                ...   
32556                  0                  0                  0   
32557                  0                  0                  0   
32558                  1                  0                  0   
32559                  1                  0                  0   
32560                  0                  0                  0   

       OCP: Exec-managerial  OCP: Farming-fishing  OCP Handlers-cleaners  \
0                         0                     0                      0   
1                         1                     0                      0   
2                         0                     0                      1   
3                         0                     0                      1   
4                         0                     0                      0   
...                     ...                   ...                    ...   
32556                     0                     0                      0   
32557                     0                     0                      0   
32558                     0                     0                      0   
32559                     0                     0                      0   
32560                     1                     0                      0   

       OCP: Machine-op-inspct  OCP: Other-service  OCP: Priv-house-serv  \
0                           0                   0                     0   
1                           0                   0                     0   
2                           0                   0                     0   
3                           0                   0                     0   
4                           0                   0                     0   
...                       ...                 ...                   ...   
32556                       0                   0                     0   
32557                       1                   0                     0   
32558                       0                   0                     0   
32559                       0                   0                     0   
32560                       0                   0                     0   

       OCP: Prof-specialty  OCP: Protective-serv  OCP: Sales  \
0                        0                     0           0   
1                        0                     0           0   
2                        0                     0           0   
3                        0                     0           0   
4                        1                     0           0   
...                    ...                   ...         ...   
32556                    0                     0           0   
32557                    0                     0           0   
32558                    0                     0           0   
32559                    0                     0           0   
32560                    0                     0           0   

       OCP: Tech-support  OCP: Transport-moving  
0                      0                      0  
1                      0                      0  
2                      0                      0  
3                      0                      0  
4                      0                      0  
...                  ...                    ...  
32556                  1                      0  
32557                  0                      0  
32558                  0                      0  
32559                  0                      0  
32560                  0                      0  

[32561 rows x 14 columns]

In [25]:
#relationship
X_relationship = dataset.iloc[:,7]
all_types_relationship = []
for item in X_relationship:
    if item in all_types_relationship:
        pass
    else:
        all_types_relationship.append(item)
print(all_types_relationship)
print(len(all_types_relationship))

[' Not-in-family', ' Husband', ' Wife', ' Own-child', ' Unmarried', ' Other-relative']
6


In [26]:
X_relationship_dummies = pd.get_dummies(X_relationship)
X_relationship_dummies = X_relationship_dummies.drop(columns=' Unmarried')
X_relationship_final = X_relationship_dummies.rename(columns={' Not-in-family':'REL: Not-in-family',
                                                              ' Husband':'REL: Husband',
                                                              ' Wife':'REL: Wife',
                                                              ' Own-child':'REL: Own-child',
                                                              ' Other-relative':'REL: Other-relative',})
X_relationship_final

REL: Husband  REL: Not-in-family  REL: Other-relative  REL: Own-child  \
0                 0                   1                    0               0   
1                 1                   0                    0               0   
2                 0                   1                    0               0   
3                 1                   0                    0               0   
4                 0                   0                    0               0   
...             ...                 ...                  ...             ...   
32556             0                   0                    0               0   
32557             1                   0                    0               0   
32558             0                   0                    0               0   
32559             0                   0                    0               1   
32560             0                   0                    0               0   

       REL: Wife  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
32556          1  
32557          0  
32558          0  
32559          0  
32560          1  

[32561 rows x 5 columns]

In [27]:
#race
X_race = dataset.iloc[:,8]
all_types_race = []
for item in X_race:
    if item in all_types_race:
        pass
    else:
        all_types_race.append(item)
print(all_types_race)
print(len(all_types_race))

[' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo', ' Other']
5


In [28]:
X_race_dummies = pd.get_dummies(X_race)
X_race_dummies = X_race_dummies.drop(columns=' Other')
X_race_final = X_race_dummies.rename(columns={' White':'RACE: White',
                                              ' Black':'RACE: Black',
                                              ' Asian-Pac-Islander':'RACE: Asian-Pac-Islander',
                                              ' Amer-Indian-Eskimo':'RACE: Amer-Indian-Eskimo'})
X_race_final

RACE: Amer-Indian-Eskimo  RACE: Asian-Pac-Islander  RACE: Black  \
0                             0                         0            0   
1                             0                         0            0   
2                             0                         0            0   
3                             0                         0            1   
4                             0                         0            1   
...                         ...                       ...          ...   
32556                         0                         0            0   
32557                         0                         0            0   
32558                         0                         0            0   
32559                         0                         0            0   
32560                         0                         0            0   

       RACE: White  
0                1  
1                1  
2                1  
3                0  
4                0  
...            ...  
32556            1  
32557            1  
32558            1  
32559            1  
32560            1  

[32561 rows x 4 columns]

In [29]:
#sex
X_sex = dataset.iloc[:,9]
all_types_sex = []
for item in X_sex:
    if item in all_types_sex:
        pass
    else:
        all_types_sex.append(item)
print(all_types_sex)
print(len(all_types_sex))

[' Male', ' Female']
2


In [30]:
X_sex_dummies = pd.get_dummies(X_sex)
X_sex_dummies = X_sex_dummies.drop(columns=' Male')
X_sex_final = X_sex_dummies.rename(columns={' Female':'SEX: Female'})
X_sex_final

SEX: Female
0                0
1                0
2                0
3                0
4                1
...            ...
32556            1
32557            0
32558            1
32559            0
32560            1

[32561 rows x 1 columns]

In [31]:
# capital gain
X_capital_gain_final = dataset.iloc[:,10]
X_capital_gain_final

0         2174
1            0
2            0
3            0
4            0
         ...  
32556        0
32557        0
32558        0
32559        0
32560    15024
Name:  capital-gain, Length: 32561, dtype: int64

In [32]:
# capital loss
X_capital_loss_final = dataset.iloc[:,11]
X_capital_loss_final

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    0
32558    0
32559    0
32560    0
Name:  capital-loss, Length: 32561, dtype: int64

In [33]:
# hours per week
X_hours_per_week = dataset.iloc[:,12]
X_hours_per_week

0        40
1        13
2        40
3        40
4        40
         ..
32556    38
32557    40
32558    40
32559    20
32560    40
Name:  hours-per-week, Length: 32561, dtype: int64

In [34]:
# native country
X_native_country = dataset.iloc[:,13]
all_types_native_country = []
for item in X_native_country:
    if item in all_types_native_country:
        pass
    else:
        all_types_native_country.append(item)
print(all_types_native_country)
print(len(all_types_native_country))

[' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico', ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada', ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland', ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos', ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic', ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan', ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland', ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong', ' Ireland', ' Hungary', ' Holand-Netherlands']
42


In [35]:
X_native_country_dummies = pd.get_dummies(X_native_country)
X_native_country_dummies = X_native_country_dummies.drop(columns=' ?')
for item in all_types_native_country:
    temp = 'CNT: ' + item
    X_native_country_dummies = X_native_country_dummies.rename(columns={item : temp})
X_native_country_final = X_native_country_dummies
X_native_country_final

CNT:  Cambodia  CNT:  Canada  CNT:  China  CNT:  Columbia  CNT:  Cuba  \
0                   0             0            0               0           0   
1                   0             0            0               0           0   
2                   0             0            0               0           0   
3                   0             0            0               0           0   
4                   0             0            0               0           1   
...               ...           ...          ...             ...         ...   
32556               0             0            0               0           0   
32557               0             0            0               0           0   
32558               0             0            0               0           0   
32559               0             0            0               0           0   
32560               0             0            0               0           0   

       CNT:  Dominican-Republic  CNT:  Ecuador  CNT:  El-Salvador  \
0                             0              0                  0   
1                             0              0                  0   
2                             0              0                  0   
3                             0              0                  0   
4                             0              0                  0   
...                         ...            ...                ...   
32556                         0              0                  0   
32557                         0              0                  0   
32558                         0              0                  0   
32559                         0              0                  0   
32560                         0              0                  0   

       CNT:  England  CNT:  France  ...  CNT:  Portugal  CNT:  Puerto-Rico  \
0                  0             0  ...               0                  0   
1                  0             0  ...               0                  0   
2                  0             0  ...               0                  0   
3                  0             0  ...               0                  0   
4                  0             0  ...               0                  0   
...              ...           ...  ...             ...                ...   
32556              0             0  ...               0                  0   
32557              0             0  ...               0                  0   
32558              0             0  ...               0                  0   
32559              0             0  ...               0                  0   
32560              0             0  ...               0                  0   

       CNT:  Scotland  CNT:  South  CNT:  Taiwan  CNT:  Thailand  \
0                   0            0             0               0   
1                   0            0             0               0   
2                   0            0             0               0   
3                   0            0             0               0   
4                   0            0             0               0   
...               ...          ...           ...             ...   
32556               0            0             0               0   
32557               0            0             0               0   
32558               0            0             0               0   
32559               0            0             0               0   
32560               0            0             0               0   

       CNT:  Trinadad&Tobago  CNT:  United-States  CNT:  Vietnam  \
0                          0                    1              0   
1                          0                    1              0   
2                          0                    1              0   
3                          0                    1              0   
4                          0                    0              0   
...                      ...                  ...      

In [36]:
# what happened above is a shame XD!
# if you followed the code you will understand what happened just don't mention it plz XD!
# (For those who didnt understand i realized there is a better way to rename the columns! XD)

In [37]:
y = dataset.iloc[:,14]
y_dummies = pd.get_dummies(y)
y_dummies

<=50K   >50K
0           1      0
1           1      0
2           1      0
3           1      0
4           1      0
...       ...    ...
32556       1      0
32557       0      1
32558       1      0
32559       1      0
32560       0      1

[32561 rows x 2 columns]

In [38]:
y_dummies = y_dummies.drop(columns=' >50K')
y_final = y_dummies.rename(columns={' <=50K': 'SALARY: <=50K'})
y_final

SALARY: <=50K
0                  1
1                  1
2                  1
3                  1
4                  1
...              ...
32556              1
32557              0
32558              1
32559              1
32560              0

[32561 rows x 1 columns]

In [39]:
# all datas are in numerical now its time to feature scaling
# i apply feature s' X_capital_loss_final' : X_capital_loss_final

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_capital_gain_final = sc.fit_transform(X_capital_gain_final.values.reshape(-1,1)).flatten()
X_capital_loss_final = sc.fit_transform(X_capital_loss_final.values.reshape(-1,1)).flatten()

In [41]:
X_capital_gain_final = pd.DataFrame({' X_capital_gain_final' : X_capital_gain_final})
X_capital_loss_final = pd.DataFrame({' X_capital_loss_final' : X_capital_loss_final})

In [42]:
X_capital_gain_final

X_capital_gain_final
0                   0.148453
1                  -0.145920
2                  -0.145920
3                  -0.145920
4                  -0.145920
...                      ...
32556              -0.145920
32557              -0.145920
32558              -0.145920
32559              -0.145920
32560               1.888424

[32561 rows x 1 columns]

In [43]:
X_capital_loss_final

X_capital_loss_final
0                   -0.21666
1                   -0.21666
2                   -0.21666
3                   -0.21666
4                   -0.21666
...                      ...
32556               -0.21666
32557               -0.21666
32558               -0.21666
32559               -0.21666
32560               -0.21666

[32561 rows x 1 columns]

In [44]:
concat_col = [X_age_final,X_workclass_final,X_education_final,X_marital_status_final,X_occupation_final,X_relationship_final,X_race_final,X_sex_final,X_capital_gain_final,X_capital_loss_final,X_hours_per_week,X_native_country_final]

In [45]:
X = pd.concat(concat_col,axis=1)

In [46]:
X = X.iloc[:,:].values

In [47]:
X

array([[39.,  0.,  0., ...,  1.,  0.,  0.],
       [50.,  0.,  0., ...,  1.,  0.,  0.],
       [38.,  0.,  0., ...,  1.,  0.,  0.],
       ...,
       [58.,  0.,  0., ...,  1.,  0.,  0.],
       [22.,  0.,  0., ...,  1.,  0.,  0.],
       [52.,  0.,  0., ...,  1.,  0.,  0.]])

In [48]:
y = y_final.iloc[:,:].values

In [49]:
y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=uint8)

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [51]:
# classification models

In [52]:
# Linear Regression
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression(random_state = 0)
clf_lr.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [53]:
y_pred_lr = clf_lr.predict(X_test)

In [54]:
clf_lr.score(X_test,y_test)

0.8447719944725933

In [55]:
from sklearn.metrics import confusion_matrix
cm_lr = confusion_matrix(y_test,y_pred_lr)
cm_lr

array([[ 968,  627],
       [ 384, 4534]], dtype=int64)

In [56]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn_clf.fit(X_train,y_train)

KNeighborsClassifier()

In [57]:
y_pred_knn = knn_clf.predict(X_test)

In [58]:
knn_clf.score(X_test,y_test)

0.8080761553815446

In [59]:
cm_knn = confusion_matrix(y_test,y_pred_knn)
cm_knn

array([[ 849,  746],
       [ 504, 4414]], dtype=int64)

In [60]:
#SVM linear
from sklearn.svm import SVC
svc_lr_clf = SVC(kernel='linear',random_state=0)
svc_lr_clf.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [61]:
y_pred_svc_lr = svc_lr_clf.predict(X_test)

In [62]:
svc_lr_clf.score(X_test,y_test)

0.8458467680024566

In [63]:
cm_svc_lr = confusion_matrix(y_test,y_pred_svc_lr)
cm_svc_lr

array([[ 986,  609],
       [ 395, 4523]], dtype=int64)

In [64]:
#kernel SVM rbf
from sklearn.svm import SVC
svc_rbf_clf = SVC(kernel='rbf',random_state=0)
svc_rbf_clf.fit(X_train,y_train)

SVC(random_state=0)

In [65]:
y_pred_svc_rbf = svc_rbf_clf.predict(X_test)

In [66]:
svc_rbf_clf.score(X_test,y_test)

0.8320282511899278

In [67]:
cm_svc_rbf = confusion_matrix(y_test,y_pred_svc_rbf)
cm_svc_rbf

array([[ 731,  864],
       [ 230, 4688]], dtype=int64)

In [68]:
# naive bayes
from sklearn.naive_bayes import GaussianNB
gnb_clf = GaussianNB()
gnb_clf.fit(X_train,y_train)

GaussianNB()

In [69]:
y_pred_gnb = gnb_clf.predict(X_test)

In [70]:
gnb_clf.score(X_test,y_test)

0.5541225241824044

In [71]:
cm_gnb = confusion_matrix(y_test,y_pred_gnb)
cm_gnb

array([[1512,   83],
       [2821, 2097]], dtype=int64)

In [72]:
#DecisionTree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc_clf = DecisionTreeClassifier(criterion='entropy',random_state=0)
dtc_clf.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [73]:
y_pred_dtc = dtc_clf.predict(X_test)

In [74]:
dtc_clf.score(X_test,y_test)

0.8180561953017043

In [75]:
cm_dtc = confusion_matrix(y_test,y_pred_dtc)
cm_dtc

array([[1047,  548],
       [ 637, 4281]], dtype=int64)

In [76]:
# Random Forest Classification
from sklearn.ensemble import RandomForestClassifier
rfc_clf = RandomForestClassifier(n_estimators=100,random_state=0,criterion='entropy')
rfc_clf.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [77]:
y_pred_rfc = rfc_clf.predict(X_test)

In [78]:
rfc_clf.score(X_test,y_test)

0.8479963150621833

In [79]:
cm_rfc = confusion_matrix(y_test,y_pred_rfc)
cm_rfc

array([[1010,  585],
       [ 405, 4513]], dtype=int64)

In [1]:

# Conclusion:
# I Applied following methods on this dataset with the following scores, sorted from the best preformance to the worst

# Random Forest Classification : 0.8479
# SVM linear                   : 0.8458
# Logistic Regression          : 0.8447
# Kernel SVM rbf               : 0.8320
# Decision Tree Classification : 0.8180
# KNN                          : 0.8080
# Naive-Bayes                  : 0.5541

# I don't know yet that why Naive Bayes had this awful results, maybe because of the non linearity of the data ...

# thanks for reading my code and i would be glad to hear about your suggestions :)


"\nConclusion:\nI Applied following methods on this dataset with the following scores, sorted from the best preformance to the worst\n\nRandom Forest Classification : 0.8479\nSVM linear                   : 0.8458\nLogistic Regression          : 0.8447\nKernel SVM rbf               : 0.8320\nDecision Tree Classification : 0.8180\nKNN                          : 0.8080\nNaive-Bayes                  : 0.5541\n\nI don't know yet that why Naive Bayes had this awful results, maybe because of the non linearity of the data ...\n\nthanks for reading my code and i would be glad to hear about your suggestions :)\n"